FROM ubuntu
RUN apt-get update

# Install Java8
RUN apt-get install -y software-properties-common vim unzip
RUN add-apt-repository -y ppa:webupd8team/java
RUN apt-get update
RUN echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
RUN echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections
RUN apt-get install -y oracle-java8-installer

# Install build tools
RUN apt-get install -y git
RUN apt-get install -y maven


ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/zookeeper-3.4.6/bin:/opt/kafka_2.11-0.9.0.0:/opt/oggbd
ENV JAVA_HOME /usr/lib/jvm/java-8-oracle
ENV LD_LIBRARY_PATH /usr/lib/jvm/java-8-oracle/jre/lib/amd64/server
ENV KAFKA_HOME /opt/kafka_2.11-0.9.0.0
ENV JRE_HOME /usr/lib/jvm/java-8-oracle/jre
ENV OGG_HOME /opt/oggbd

CMD ["bash"]
